### ISSUE TITLE
Why normalize the mask_token for Swin but not for PVT?

### ISSUE THREAD

**Issue by Haochen-Wang409** [implus/UM-MAE#10]
Hi, sorry to bother you again.

I found differences in ```models_mae_swin.py``` and ```models_mae_pvt.py``` when dealing with ```mask_token```.
https://github.com/implus/UM-MAE/blob/main/models_mae_swin.py#L461-L466
https://github.com/implus/UM-MAE/blob/main/models_mae_pvt.py#L316-L320

In ```models_mae_swin.py```, ```mask_token``` are first normalized by ```self.patch_embed```, while in ```models_mae_pvt.py``` do not. Why?

**Comment by implus** [comment]
Hi, the reason is that officially Swin defaults to normalize patch embeddings but pvt doesn't.

**Comment by Haochen-Wang409** [comment]
Thanks for your reply.
