### ISSUE TITLE
Failed to pretrain a model with multi-nodes

### ISSUE THREAD

**Issue by Haochen-Wang409** [implus/UM-MAE#12]
Hi, sorry to bother you again.

I failed to train UM-MAE with multi-node, which will be stuck here for each node:
```
*****************************************
| distributed init (rank 5): env://, gpu 5
| distributed init (rank 3): env://, gpu 3
| distributed init (rank 1): env://, gpu 1
| distributed init (rank 0): env://, gpu 0
| distributed init (rank 4): env://, gpu 4
| distributed init (rank 7): env://, gpu 7
| distributed init (rank 2): env://, gpu 2
| distributed init (rank 6): env://, gpu 6
```

However, MAE is able to be trained with multi-nodes.

**Comment by implus** [comment]
Hi, since we only have single-node environment, it would be hard for us to debug under the multi-node case. Our experiments are all performed on a single node with 8 GPUs. I'm sorry.

**Comment by Haochen-Wang409** [comment]
Okay then, thanks for your reply.
