### ISSUE TITLE
How to produce reconstruction visualizations during pre-training?

### ISSUE THREAD

**Issue by Asers387** [implus/UM-MAE#3]
I haven't been able to produce images to visualize the effectiveness of the model during each epoch of pre-training. I was wondering if a method was included in the code to do this, or if you could provide the code to do this, just like in figure 8 of your paper where we can see the original picture, the mask and the reconstruction side-by-side.

Thanks!

**Comment by implus** [comment]
We will provide the visualization codes very recently（It's in the TODO list of README.md）. Thanks for your patience~

**Comment by implus** [comment]
please see commit: 77f1af5e14d85bb4b0ce6b74ca28cf2afe27de8d
The code is provide in visual/ folder.
Thanks again~
