### ISSUE TITLE
No such file or directory: '/data/datasets/mini-imagenet/train.txt'

### ISSUE THREAD

**Issue by RyanZRH** [implus/UM-MAE#5]
when i was pretraining，it comes up with this error. Is txt file a must？ It does not need this file when pretraining vanilla mae.

**Comment by implus** [comment]
Check the issue here. https://github.com/implus/UM-MAE/issues/1#issuecomment-1135693812
We've already provide the train.txt/val.txt in our repo.

**Comment by RyanZRH** [comment]
> 

thanks!
