### ISSUE TITLE
Question about the Uniform Sampling

### ISSUE THREAD

**Issue by Andy1621** [implus/UM-MAE#7]
Thanks for your great job.
I have read the code about `Uniform Sampling`, and it's interesting to realize it in `mask_transform.py`. However, I am confused about the limitation as follows：
https://github.com/implus/UM-MAE/blob/5058a0578e1e90b4693e720605a59e29a1088912/mask_transform.py#L27

For example,
```python
# Give
self.height = self.width = 14
self.num_patches = 196
# We have
len(candidate_list) = 196 / 2 = 98
```
In this way, the candidate_list is repeated for `98 // 4 = 24` times. In fact, `Grid Sampling` is a special case of `Uniform Sampling`.   However, it seems impossible to repeat the same mask pattern for `196 // 4 = 49` under the above limitation.

Should the limitation be set as follows?
```python
if len(candidate_list) // 4 >= self.num_patches // 4:
# i.e.,
if len(candidate_list) >= self.num_patches:
```
Thus `Grid Sampling` may be realized when shuffling.

Of course, such a problem may not affect the result. In contrast, it avoids `Grid Sampling`, leading to better convergence as in Table1. But I am just confused about the reason for the limitation.

**Comment by implus** [comment]
Yes, I believe that your consideration is more reasonable. Thanks a lot for your advise, and I will check the effect later when available.

**Comment by Andy1621** [comment]
Thanks for your reply!
